spring:
  datasource:
    url: jdbc:postgresql://dpg-ctgo7q52ng1s738loptg-a.oregon-postgres.render.com/database_49xm
    username: database_49xm_user
    password: KLutLmi3daUjLPpU70GgmzskJc6lW2v5
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  tomcat:
    accesslog:
      enabled: true